# Generated by Django 5.2.6 on 2025-09-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('choices', models.JSONField()),
                ('consequences', models.JSONField()),
                ('ethical_scores', models.JSONField()),
            ],
        ),
    ]
