# Generated by Django 5.2.6 on 2025-09-19 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='selected_choice',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
